### ISSUE TITLE
Difference with `cli-matic`?

### ISSUE THREAD

**Issue by kxygk** [lambdaisland/cli#1]
Would be nice if there was an explicit comparison with [cli-matic](https://github.com/l3nz/cli-matic) and a rational for a new library in this space (just curious .. haven't used either yet)

**Comment by plexus** [comment]
Please reserve issues for actual issues.

**Comment by plexus** [comment]
I quickly skimmed their readme, seems there are some differences in philosophy, but the most salient difference is that lamdaisland/cli does not have any dependencies.
